import { Activity, User, Category, Review } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Hiking', icon: '🥾', count: 234, color: 'hsl(142, 71%, 45%)' },
  { id: '2', name: 'Photography', icon: '📸', count: 189, color: 'hsl(262, 83%, 58%)' },
  { id: '3', name: 'Cooking', icon: '🍳', count: 156, color: 'hsl(16, 85%, 60%)' },
  { id: '4', name: 'Sports', icon: '⚽', count: 312, color: 'hsl(217, 91%, 60%)' },
  { id: '5', name: 'Music', icon: '🎵', count: 98, color: 'hsl(340, 82%, 52%)' },
  { id: '6', name: 'Art', icon: '🎨', count: 145, color: 'hsl(38, 92%, 50%)' },
  { id: '7', name: 'Gaming', icon: '🎮', count: 267, color: 'hsl(280, 67%, 50%)' },
  { id: '8', name: 'Yoga', icon: '🧘', count: 178, color: 'hsl(168, 76%, 42%)' },
  { id: '9', name: 'Book Club', icon: '📚', count: 89, color: 'hsl(30, 80%, 55%)' },
  { id: '10', name: 'Volunteering', icon: '🤝', count: 123, color: 'hsl(200, 70%, 50%)' },
];

export const activities: Activity[] = [
  {
    id: '1',
    title: 'Sunrise Hike at Golden Gate',
    description: 'Join us for a breathtaking sunrise hike along the Golden Gate Bridge trail. We\'ll meet at the parking lot and hike together to the best viewpoint. All fitness levels welcome!',
    category: 'Hiking',
    date: '2026-04-20',
    time: '06:00',
    city: 'San Francisco',
    location: 'Golden Gate Bridge Parking Lot',
    bannerImage: 'https://images.unsplash.com/photo-1501554728187-ce583db33af7?w=800&q=80',
    hostId: '1',
    hostName: 'Alex Chen',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80',
    participantLimit: 20,
    currentParticipants: 14,
    difficulty: 'moderate',
    tags: ['outdoor', 'nature', 'fitness', 'sunrise'],
    isPublic: true,
    safetyInstructions: 'Bring water, wear comfortable shoes, bring a flashlight.',
    agenda: ['06:00 - Meet at parking lot', '06:15 - Start hike', '07:30 - Reach viewpoint', '08:00 - Group photos', '08:30 - Return'],
    rules: ['No littering', 'Stay on marked trails', 'Respect wildlife'],
    requiredItems: ['Water bottle', 'Comfortable shoes', 'Flashlight', 'Light jacket'],
    createdAt: '2026-04-10',
  },
  {
    id: '2',
    title: 'Street Photography Walk',
    description: 'Explore the vibrant streets of downtown and capture amazing shots. Whether you\'re using a DSLR or your phone, everyone is welcome!',
    category: 'Photography',
    date: '2026-04-22',
    time: '14:00',
    city: 'New York',
    location: 'Times Square Meeting Point',
    bannerImage: 'https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=800&q=80',
    hostId: '2',
    hostName: 'Maya Johnson',
    hostAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80',
    participantLimit: 15,
    currentParticipants: 8,
    difficulty: 'easy',
    tags: ['photography', 'urban', 'creative', 'walking'],
    isPublic: true,
    agenda: ['14:00 - Meet & greet', '14:30 - Photography walk begins', '16:00 - Coffee break & share shots', '17:00 - Wrap up'],
    createdAt: '2026-04-11',
  },
  {
    id: '3',
    title: 'Italian Pasta Masterclass',
    description: 'Learn to make authentic Italian pasta from scratch! We\'ll be making three types of pasta with homemade sauces. All ingredients provided.',
    category: 'Cooking',
    date: '2026-04-25',
    time: '18:00',
    city: 'Los Angeles',
    location: 'Community Kitchen, Downtown LA',
    bannerImage: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    hostId: '3',
    hostName: 'Marco Rossi',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80',
    participantLimit: 12,
    currentParticipants: 12,
    difficulty: 'easy',
    tags: ['cooking', 'italian', 'food', 'social'],
    isPublic: true,
    createdAt: '2026-04-09',
  },
  {
    id: '4',
    title: 'Weekend Soccer Tournament',
    description: 'Friendly 5-a-side soccer tournament. Teams will be formed on the spot. Come ready to play and have fun!',
    category: 'Sports',
    date: '2026-04-26',
    time: '10:00',
    city: 'Chicago',
    location: 'Lincoln Park Fields',
    bannerImage: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80',
    hostId: '4',
    hostName: 'Jordan Miller',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80',
    participantLimit: 30,
    currentParticipants: 22,
    difficulty: 'intense',
    tags: ['sports', 'soccer', 'competition', 'outdoor'],
    isPublic: true,
    createdAt: '2026-04-08',
  },
  {
    id: '5',
    title: 'Open Mic Night - Acoustic Sessions',
    description: 'Bring your guitar, your voice, or just your ears! A cozy evening of live acoustic performances in an intimate setting.',
    category: 'Music',
    date: '2026-04-23',
    time: '19:00',
    city: 'Austin',
    location: 'The Velvet Lounge',
    bannerImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
    hostId: '5',
    hostName: 'Sam Rivera',
    hostAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80',
    participantLimit: 40,
    currentParticipants: 28,
    difficulty: 'easy',
    tags: ['music', 'acoustic', 'live', 'social'],
    isPublic: true,
    createdAt: '2026-04-07',
  },
  {
    id: '6',
    title: 'Watercolor Painting Workshop',
    description: 'Discover the joy of watercolor painting. No experience needed—we provide all materials and step-by-step guidance.',
    category: 'Art',
    date: '2026-04-27',
    time: '11:00',
    city: 'Portland',
    location: 'Art Space Gallery',
    bannerImage: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80',
    hostId: '6',
    hostName: 'Lila Park',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&q=80',
    participantLimit: 16,
    currentParticipants: 10,
    difficulty: 'easy',
    tags: ['art', 'painting', 'creative', 'relaxing'],
    isPublic: true,
    createdAt: '2026-04-06',
  },
  {
    id: '7',
    title: 'Morning Yoga in the Park',
    description: 'Start your weekend with a rejuvenating yoga session in the park. Suitable for all levels. Bring your own mat.',
    category: 'Yoga',
    date: '2026-04-21',
    time: '07:30',
    city: 'San Diego',
    location: 'Balboa Park',
    bannerImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    hostId: '7',
    hostName: 'Nina Patel',
    hostAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&q=80',
    participantLimit: 25,
    currentParticipants: 18,
    difficulty: 'easy',
    tags: ['yoga', 'wellness', 'outdoor', 'morning'],
    isPublic: true,
    createdAt: '2026-04-05',
  },
  {
    id: '8',
    title: 'Retro Game Night',
    description: 'Relive the classics! We\'re setting up SNES, N64, and arcade cabinets. Snacks and drinks provided. Come play!',
    category: 'Gaming',
    date: '2026-04-24',
    time: '20:00',
    city: 'Seattle',
    location: 'Level Up Arcade Bar',
    bannerImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&q=80',
    hostId: '8',
    hostName: 'Chris Wong',
    hostAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&q=80',
    participantLimit: 30,
    currentParticipants: 25,
    difficulty: 'easy',
    tags: ['gaming', 'retro', 'social', 'fun'],
    isPublic: true,
    createdAt: '2026-04-04',
  },
];

export const currentUser: User = {
  id: '1',
  name: 'Alex Chen',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80',
  bio: 'Adventure seeker and community builder. Love hiking, cooking, and meeting new people through shared experiences.',
  interests: ['Hiking', 'Cooking', 'Photography', 'Yoga'],
  joinedDate: '2025-06-15',
  activitiesHosted: 12,
  activitiesJoined: 34,
  streak: 7,
  badges: [
    { id: '1', name: 'Trailblazer', icon: '🏔️', description: 'Hosted 10+ activities' },
    { id: '2', name: 'Social Butterfly', icon: '🦋', description: 'Joined 25+ activities' },
    { id: '3', name: 'Streak Master', icon: '🔥', description: '7-day activity streak' },
    { id: '4', name: 'Early Bird', icon: '🐦', description: 'Joined 5 morning activities' },
  ],
};

export const reviews: Review[] = [
  { id: '1', userId: '2', userName: 'Maya Johnson', userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80', rating: 5, comment: 'Amazing experience! The views were absolutely breathtaking and Alex was a fantastic host.', date: '2026-03-15' },
  { id: '2', userId: '3', userName: 'Marco Rossi', userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80', rating: 4, comment: 'Great hike, well organized. Would love to join again!', date: '2026-03-10' },
  { id: '3', userId: '5', userName: 'Sam Rivera', userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80', rating: 5, comment: 'Met so many amazing people. This is exactly what I needed!', date: '2026-03-05' },
];

export const testimonials = [
  { name: 'Sarah K.', role: 'Community Member', quote: 'LinkUp helped me find my hiking tribe. I\'ve made lifelong friends through weekend adventures!', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&q=80' },
  { name: 'David M.', role: 'Activity Host', quote: 'As someone new to the city, LinkUp was a game-changer. I now host weekly cooking sessions!', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80' },
  { name: 'Priya R.', role: 'Active User', quote: 'No endless scrolling, no drama — just real people doing real things together.', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&q=80' },
];
